version: '3'

services:
  hue:
    image: gethue/hue:latest
    container_name: hue
    networks:
      - hive_hue_network
    ports:
      - "8888:8888"
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    environment:
      - HUE_DATABASE_ENGINE=django.db.backends.mysql
      - HUE_DATABASE_NAME=hue
      - HUE_DATABASE_USER=hueuser
      - HUE_DATABASE_PASSWORD=huepassword
      - HUE_DATABASE_HOST=db
      - HUE_DATABASE_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: hue-db
    networks:
      - hive_hue_network
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=hue
      - MYSQL_USER=hueuser
      - MYSQL_PASSWORD=huepassword
    volumes:
      - db_data:/var/lib/mysql

networks:
  hive_hue_network:
    external: true

volumes:
  db_data:
